[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

# Configuración para el entorno de producción
[context.production.environment]
  VITE_APP_ENV = "production"

# Configuración para despliegues de ramas
[context.branch-deploy.environment]
  VITE_APP_ENV = "staging"

# Configuración para despliegues de vista previa
[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"

# Redirección principal para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección para la API - Actualiza la URL con la de tu backend real
[[redirects]]
  from = "/api/*"
  to = "https://sigepa-backend.your-backend-service.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://sigepa.netlify.app" }

# Opciones de seguridad recomendadas
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://sigepa.netlify.app https://sigepa-backend.your-backend-service.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;" 