# Configuración de construcción para el sitio web SIGEPA alojado en Netlify
[build]
  command = "npm run build"    # Comando para construir la aplicación
  publish = "dist"             # Directorio donde se encuentra el sitio compilado
  environment = { NODE_VERSION = "20", SECRETS_SCAN_ENABLED = "false" }  # Versión de Node.js a usar y desactivar escaneo de secretos

# Variables de entorno para producción
[context.production.environment]
  VITE_APP_ENV = "production"

# Variables de entorno para despliegues de ramas
[context.branch-deploy.environment]
  VITE_APP_ENV = "staging"

# Variables de entorno para vistas previas
[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"

# Redirección para Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección para la API - Esta es la parte crucial para conectarse al backend
# La URL debe apuntar a tu backend en Render.com
[[redirects]]
  from = "/api/*"
  to = "https://eva3-proyecto-ti.onrender.com/api/:splat"  # URL de tu backend en Render
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*", 
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
  }

# Opciones de seguridad recomendadas
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Política de seguridad actualizada con la URL del backend
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://sigepa.netlify.app https://eva3-proyecto-ti.onrender.com https://*.amazonaws.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;" 