[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "20" }

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "netlify/functions"
  functionsPort = 9999

# Configuración para el entorno de producción
[context.production.environment]
  VITE_APP_ENV = "production"
  MYSQL_HOST = "sigepa-db-id.cfy6uk6aipzc.us-east-1.rds.amazonaws.com"
  MYSQL_USER = "admin"
  MYSQL_PASSWORD = "#SnKKerV!tH4gRf"
  MYSQL_DATABASE = "sigepa_db"

# Configuración para despliegues de ramas
[context.branch-deploy.environment]
  VITE_APP_ENV = "staging"

# Configuración para despliegues de vista previa
[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"

# Redirección principal para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección para la API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Opciones de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://sigepa.netlify.app; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"